### ISSUE TITLE
Using Docker Compose: error Couldn't find a package.json file in "/app

### ISSUE THREAD

**Issue by lsaiken** [docker/getting-started#102] opened 2020-12-05 06:09 UTC
When executing docker-compose up -d, I received this error above when running from the root folder and the app folder.  In order to get it to work, I had to add "**cd app** && yarn install && yarn run dev" to the app service command.  Can someone explain what's going on here and is this just a workaround?

**Comment by Patronics** [comment] 2021-01-06 07:16
this issue seems to be a duplicate of #76, hopefully the answers there help!

**Comment by atubo2012** [comment] 2021-01-26 09:56
> When executing docker-compose up -d, I received this error above when running from the root folder and the app folder. In order to get it to work, I had to add "**cd app** && yarn install && yarn run dev" to the app service command. Can someone explain what's going on here and is this just a workaround?

Hi,Isaiken, I encountered same issue , if you have solved the issue, please! Many thanks.

**Comment by atubo2012** [comment] 2021-01-26 10:33
> > When executing docker-compose up -d, I received this error above when running from the root folder and the app folder. In order to get it to work, I had to add "**cd app** && yarn install && yarn run dev" to the app service command. Can someone explain what's going on here and is this just a workaround?
> 
> Hi,Isaiken, I encountered same issue , if you have solved the issue, please! Many thanks.

Solved. 
Firstly,Download the source code from the link in following circle ,then unzip app.zip. Let the package.json to be in path /root/app.
![image](https://user-images.githubusercontent.com/30145089/105833920-d420ff00-6004-11eb-9787-dadae1140bb2.png)

Secondly,In the docker-compose.yml set like this:

![image](https://user-images.githubusercontent.com/30145089/105833605-670d6980-6004-11eb-8d42-167ea2ab9db8.png)

**Comment by mohammedfellak** [comment] 2022-01-20 20:18
I had the same issue, And it happened after i've changed the root folder name
Brought the name back and that solved the issue

**Comment by sagarchaudhary1994** [comment] 2022-12-17 17:20
> > > When executing docker-compose up -d, I received this error above when running from the root folder and the app folder. In order to get it to work, I had to add "**cd app** && yarn install && yarn run dev" to the app service command. Can someone explain what's going on here and is this just a workaround?
> > 
> > 
> > Hi,Isaiken, I encountered same issue , if you have solved the issue, please! Many thanks.
> 
> Solved. Firstly,Download the source code from the link in following circle ,then unzip app.zip. Let the package.json to be in path /root/app. ![image](https://user-images.githubusercontent.com/30145089/105833605-670d6980-6004-11eb-8d42-167ea2ab9db8.png)
> 
> Secondly,In the docker-compose.yml set like this: ![image](https://user-images.githubusercontent.com/30145089/105833920-d420ff00-6004-11eb-9787-dadae1140bb2.png)

Thanks, this worked.

**Closed** 2022-12-21 12:59 UTC
