### ISSUE TITLE
Getting-Started won't build - error on load metadata

### ISSUE THREAD

**Issue by GittyUp10** [docker/getting-started#294] opened 2022-08-10 15:29 UTC
PS C:\Users\Bigdog3> docker cp repo:/git/getting-started/ .

docker cp repo:/git/getting-started/ .docker run --name repo alpine/git clone https://github.com/docker/getting-started.git
unknown flag: --name
See 'docker cp --help'.
PS C:\Users\Bigdog3> docker cp repo:/git/getting-started/ .
PS C:\Users\Bigdog3> cd getting-started
PS C:\Users\Bigdog3\getting-started> docker build -t docker101tutorial .
[+] Building 15.0s (6/6) FINISHED
 => [internal] load build definition from Dockerfile        0.0s
 => => transferring dockerfile: 1.12kB                      0.0s
 => [internal] load .dockerignore                           0.0s
 => => transferring context: 52B                            0.0s
 => ERROR [internal] load metadata for docker.io/library/  14.9s
 => CANCELED [internal] load metadata for docker.io/libra  10.1s
 => ERROR [internal] load metadata for docker.io/library/  10.1s
 => [auth] library/nginx:pull token for registry-1.docker.  0.0s
 > [internal] load metadata for docker.io/library/node:12-alpine:------        
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head "https://registry-1.docker.io/v2/library/node/manifests/12-alpine": net/http: TLS handshake timeout----------------------------------XXPS C:\Users\Bigdog3\getting-started> docker run -d -p 80:80 --name docker-tutorial docker101tutorial-----------------------------------------------------------XXUnable to find image 'docker101tutorial:latest' locally-------------------------XXdocker: Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: TLS handshake timeout.---------------------------------------------------XXSee 'docker run --help'.
PS C:\Users\Bigdog3\getting-started> cd getting-started
cd : Cannot find path-----------------------------------------------------------XX'C:\Users\Bigdog3\getting-started\getting-started' because it
does not exist.
At line:1 char:1
+ cd getting-started
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Bigdog.
   ..getting-started:String) [Set-Location], ItemNotFoundExcep
  tion
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell
   .Commands.SetLocationCommand

PS C:\Users\Bigdog3\getting-started> docker build -t docker101tutorial .       
[+] Building 10.5s (6/6) FINISHED
 => [internal] load build definition from Dockerfile        0.0s
 => => transferring dockerfile: 32B                         0.0s
 => [internal] load .dockerignore                           0.0s
 => => transferring context: 34B                            0.0s
 => ERROR [internal] load metadata for docker.io/library/  10.3s
 => CANCELED [internal] load metadata for docker.io/libra  10.1s
 => ERROR [internal] load metadata for docker.io/library/  10.1s
 => [auth] library/nginx:pull token for registry-1.docker.  0.0s
------
 > [internal] load metadata for docker.io/library/nginx:alpine:
------
------
 > [internal] load metadata for docker.io/library/node:12-alpine:------        
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head "https://registry-1.docker.io/v2/library/node/manifests/12-alpine": net/http: TLS handshake timeout
PS C:\Users\Bigdog3\getting-started>^C
PS C:\Users\Bigdog3\getting-started>

**Comment by mikesir87** [comment] 2022-11-25 04:15
Hi there and thanks for filing an issue! We apologize it's taken so long to get back to you. We're curious if you ever got through your problem or if you might still need help. Some of these TLS/network issues can be temporary, so want to make sure of that or if you still need help.

**Comment by jltrevizon** [comment] 2022-11-25 13:31
same problem.
![image](https://user-images.githubusercontent.com/22945459/203996146-60144de3-eac0-422b-8659-1e428e924dab.png)

**Comment by mikesir87** [comment] 2022-11-25 14:09
@jltrevizon Is the problem pulling the image only occurring when doing a build? Try running `docker pull nginx:alpine` and see what results you get. 

As another question, are you currently logged in to Docker Desktop/the CLI or working anonymously?

**Comment by jltrevizon** [comment] 2022-11-25 18:21
> @jltrevizon Is the problem pulling the image only occurring when doing a build? Try running `docker pull nginx:alpine` and see what results you get.
> 
> As another question, are you currently logged in to Docker Desktop/the CLI or working anonymously?

Docker desktop on Window

**Comment by jltrevizon** [comment] 2022-11-25 18:30
![image](https://user-images.githubusercontent.com/22945459/204039440-278319b9-1f37-4d55-a077-4d2ba0d20d74.png)
Now it did work, but I had that error since yesterday until I gave up, today I resumed work and now it works.

**Comment by chukwuemekaodigwe** [comment] 2022-12-01 09:23
> @jltrevizon Is the problem pulling the image only occurring when doing a build? Try running `docker pull nginx:alpine` and see what results you get.
> 
> As another question, are you currently logged in to Docker Desktop/the CLI or working anonymously?

Must I login on docker desktop for it work? I'm using the cli ?? Any solutions

**Comment by jltrevizon** [comment] 2022-12-01 11:34
> > @jltrevizon Is the problem pulling the image only occurring when doing a build? Try running `docker pull nginx:alpine` and see what results you get.
> > As another question, are you currently logged in to Docker Desktop/the CLI or working anonymously?
> 
> Must I login on docker desktop for it work? I'm using the cli ?? Any solutions

yes, that's how it worked for me

**Comment by mikesir87** [comment] 2022-12-02 20:22
> Must I login on docker desktop for it work?

@chukwuemekaodigwe You shouldn't need to. I was asking that because rate limits might be applying and you are rate limited differently depending on whether you are authenticated or not. Have you been able to get it to work or are you still stuck?

@jltrevizon Glad to hear it's working for you now!

**Comment by chukwuemekaodigwe** [comment] 2022-12-02 22:20
It works. I just retried it, it went. Maybe it caused by network error.

Thanks

**Comment by mikesir87** [comment] 2022-12-02 23:21
Sounds good! Glad to hear it's working for you now. I'll go ahead and close this issue then. Feel free to open another one if you run into any other problems!

**Closed** 2022-12-02 23:21 UTC
