### ISSUE TITLE
Bind Mounts on windows not working

### ISSUE THREAD

**Issue by Nyerca** [docker/getting-started#100] opened 2020-10-27 09:24 UTC
I'm trying to understand why i cant execute this command, i'm currently inside getting-started\app (on Windows) and i get errors:

`docker run -dp 3000:3000 \
    -w /app -v "$(pwd):/app" \
    node:12-alpine \
    sh -c "yarn install && yarn run dev"`

This opens a message saying docker wants to access:  C:\PATH\getting-started\app;C (with the weird ;C at the end)

If i change the code in this way it goes away:
    -w //app -v "$(pwd)://app" \

it starts a container which gets closed immediatly with an error:
error Couldn't find a package.json file in "/app"

I don't understand why, is the dockerfile or the package.json missplaced? I tried to look at other similar issues on github but i was unable to solve my problem.

Thank you!

UPDATE:
Asked a friend, seems like there is a problem with paths that has to be written not in windows style:
So from getting-started/app i did:

docker run -dp 3000:3000 \
-w //app -v "//c/Users/blabla/app_test/getting-started":/app \
    node:12-alpine \
    sh -c "yarn install && yarn run dev"

note the -v has the <host directory>:<target directory> in which the host directory is written in a Linux format

note: if in the -w i would put only: -w /app it would trigger an error:
docker: Error response from daemon: the working directory 'C:/Program Files/Git/app' is invalid, it needs to be an absolute path.
(With the weird git path)

**Comment by diligent176** [comment] 2021-01-24 15:39
Nice!  This helped me complete the tutorial on Windows 10.  
Thanks for the tip, this worked for me:

```
docker run -dp 3000:3000 -w /app -v "//c/github/todo-nodeapp:/app" node:12-alpine sh -c "yarn install && yarn run dev"
```

**Comment by AfroBadger** [comment] 2021-01-27 09:50
Glad I found this thread.  I too had the same problem.  Not sure if it is something new with WSL2.  

I will try and set an amendment,

**Comment by Franz333** [comment] 2021-02-12 19:29
Awsome.. thanks a lot.. was stuck all day on this..
It's annoying.. your are following a tutorial and you get more focused trying to solve the problems than actually learning :-(

**Comment by mcarson1** [comment] 2021-05-04 16:49
I had to be in the right directory (where I downloaded and unzipped the app).

**Comment by Emprah** [comment] 2021-05-06 08:14
For me, this worked:
`PS C:\...\getting-started\app> docker run -dp 3000:3000 -v "$(pwd):/app/" node:12-alpine sh -c "cd app && yarn install && yarn run dev"`

The important bits were:
- Using Powershell (instead of git bash), to avoid escaping problems
- Directly going into the app directory instead of using the -w parameter (docker complaining about my path not being an absolute path and whatnot)
- Adding "cd app"as the first shell command

**Comment by confessore** [comment] 2021-06-09 17:22
confirmed.
before running this command navigate to the "app" directory that came with "getting-started" 

since "${PWD}" is basically the command to get the current directory path, you need to be inside of the proper directory to the correct path to run the command!

**Comment by dustan22** [comment] 2022-02-11 14:57
> Glad I found this thread. I too have the same problem. Not sure if it is something new with WSL2.
> 
> Docker did first accept the new command syntax `//drive/appdir:/app` , but now it is responding the same way as before with the container exiting. Any way I can see what error is causing the container to exit?

If you use the docker desktop app, you can click on the container name and it will try to create the container and show you any errors.

**Comment by mikesir87** [comment] 2022-12-19 22:19
Hi all! Apologies for the delay in responding to this issue. The tutorial has gone through several improvements since this issue was created, some of which I anticipate would have resolved this issue. In addition, there are a few answers that have been posted here already. Therefore, I'm going to go ahead and close it.

If you have future questions or issues, feel free to create a new issue and we'll be happy to help out (and will respond much more quickly too!). Thanks all!

**Closed by mikesir87** 2022-12-19 22:19 UTC

**Comment by RandyBetancourt** [comment] 2023-04-28 21:39
I know this closed, but for others after me--the issue I ran into was
```The engine "node" is incompatible with this module. Expected version "^14.15.0 || ^16.10.0 || >=18.0.0". Got "12.22.12"```
I got around it by adding the --ignore-engines arg:
```PS> docker run -dp 3000:3000 -v "$(pwd):/app/" node:12-alpine sh -c "cd app && yarn install --ignore-engines && yarn run dev"```
