### ISSUE TITLE
ToDo App (localhost:3000) shows no UI in Browser

### ISSUE THREAD

**Issue by Monte-Christo** [docker/getting-started#9] opened 2020-04-06 15:30 UTC
When I start the container with the node app, everything looks fine, but upon navigating to localhost:3000 the browser window is empty (see screenshot):

![Capture](https://user-images.githubusercontent.com/8224318/78575535-c909a200-782b-11ea-92d3-4875afbc68fc.PNG)

The logs contain exactly two lines:

`Using sqlite database at /etc/todos/todo.db
Listening on port 3000`

This is on Docker Desktop CE Stable for WIndows 2.2.0.5, Docker Desktop CE Edge 2.2.3.0 under Windows 10 Pro 2004 and Windows 10 Enterprise 19.03. Tested with Chrome, Firefox, and Edge (all latest versions).

**Comment by mikesir87** [comment] 2020-04-06 16:48
Odd. Do you have any errors appearing in the browser's console? It seems that the stylesheet is loading, as the background is grey, but the app just hasn't started up.

**Comment by Monte-Christo** [comment] 2020-04-06 17:54
I am no expert in this kind of debugging. Here is the console log from Chrome:

`DevTools failed to parse SourceMap: chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map
DevTools failed to parse SourceMap: chrome-extension://bhmmomiinigofkjcapegjjndpbikblnp/libs/bundle.min.js.map
DevTools failed to parse SourceMap: chrome-extension://bhmmomiinigofkjcapegjjndpbikblnp/libs/lodash.min.js.map
DevTools failed to parse SourceMap: chrome-extension://gnldpbnocfnlkkicnaplmkaphfdnlplb/ContentScript/CustomisedWorkItemMessaging.js.map
DevTools failed to parse SourceMap: chrome-extension://gnldpbnocfnlkkicnaplmkaphfdnlplb/ContentScript/CaptureBrowserEvent.js.map
DevTools failed to parse SourceMap: http://localhost:3000/css/bootstrap.min.css.map
DevTools failed to parse SourceMap: chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map
localhost/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:3000/js/react.production.min.js' with computed SHA-256 integrity '9+vSqarg29SkRZPgHqGhak6fAnATU3fEPkN1Yw+i25s='. The resource has been blocked.
localhost/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:3000/js/react-dom.production.min.js' with computed SHA-256 integrity 'sp8nn9AyhHakaxibzqQsIsuF/fNQ6UDhwJOMAERMsxs='. The resource has been blocked.
localhost/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:3000/js/react-bootstrap.js' with computed SHA-256 integrity 'BYDF/Xl311qx4ajriU87g3bKXNm6Q7wfjmfDjZvOPLs='. The resource has been blocked.
localhost/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:3000/js/babel.min.js' with computed SHA-256 integrity '0wja2UfK4fkY4sWYgLIp9NtcZLKen7TjG98MwaHFREw='. The resource has been blocked.
DevTools failed to parse SourceMap: http://localhost:3000/css/bootstrap.min.css.map
DevTools failed to parse SourceMap: chrome-extension://bhmmomiinigofkjcapegjjndpbikblnp/libs/bundle.min.js.map
DevTools failed to parse SourceMap: chrome-extension://bhmmomiinigofkjcapegjjndpbikblnp/libs/lodash.min.js.map
DevTools failed to parse SourceMap: chrome-extension://gnldpbnocfnlkkicnaplmkaphfdnlplb/ContentScript/CustomisedWorkItemMessaging.js.map
DevTools failed to parse SourceMap: chrome-extension://gnldpbnocfnlkkicnaplmkaphfdnlplb/ContentScript/CaptureBrowserEvent.js.map`

Here the one from Edge:

`HTML1300: Navigation occurred.
about:blank (1,1)

HTML1527: DOCTYPE expected. Consider adding a valid HTML5 doctype: "<!DOCTYPE html>".
about:blank (1,1)

HTML1300: Navigation occurred.
localhost:3000 (1,1)

CONSOLE1810304: console.memory is not implemented and will return 0 for all attributes. Please use the memory profiler to monitor memory utilization.

SEC7136: [Integrity] The origin 'http://localhost:3000' failed an integrity check for a script resource at 'http://localhost:3000/js/react.production.min.js'.

SEC7136: [Integrity] The origin 'http://localhost:3000' failed an integrity check for a script resource at 'http://localhost:3000/js/react-dom.production.min.js'.

SEC7136: [Integrity] The origin 'http://localhost:3000' failed an integrity check for a script resource at 'http://localhost:3000/js/react-bootstrap.js'.

SEC7136: [Integrity] The origin 'http://localhost:3000' failed an integrity check for a script resource at 'http://localhost:3000/js/babel.min.js'.
`

And from Firefox:

`
None of the “sha256” hashes in the integrity attribute match the content of the subresource. 4 localhost:3000
None of the “sha256” hashes in the integrity attribute match the content of the subresource. localhost:3000
None of the “sha256” hashes in the integrity attribute match the content of the subresource. localhost:3000
None of the “sha256” hashes in the integrity attribute match the content of the subresource. localhost:3000
Sending APH request... antiphishing.js:16:108112
Source map error: Error: request failed with status 404
Resource URL: http://localhost:3000/css/bootstrap.min.css
Source Map URL: bootstrap.min.css.map​
`

**Comment by mikesir87** [comment] 2020-04-06 19:23
Thanks for the feedback. So, the browser is failing its Sub-resource Integrity (SRI) checks. In case you aren't aware of what that is, the `index.html` includes each of these scripts, but includes an expected hash for each of the files. Once the file is downloaded, the file is hashed by the browser and compared to the expected hash. If the hashes don't match, the code isn't executed. This is particularly important when trying to load scripts from third-party servers (such as CDNs). Since everything is coming through localhost, it's not _as_ important, although still a good practice.

Now the question... why are you getting different hashes? I just checked on my local machine and the hashes are still valid based on what's in the index.html file. So, this probably means there's something changing the files on your machine. Do you have a set of extensions on each of your browsers? If so, can you try running in an incognito/private window with those disabled and see if you get the same result? Are you using a corporate or other proxy server? Those typically aren't involved on localhost-based requests, but still worth asking.

**Comment by Monte-Christo** [comment] 2020-04-07 06:26
Same result in Incognito Mode on all three browsers. Also checked with IE, no dice, even though the errors look different. I tried both on my work laptop and on my home laptop with identical results. The only things common on all browsers are LastPass and AdBlock plus.

**Comment by t3hcr** [comment] 2020-04-19 01:21
Having a similar issue as what @Monte-Christo submitted above, (on Docker Desktop CE Edge 2.2.3.0 running on Windows 10 Pro 2004) 

I'm getting back into learning containers and can help too if needed.  

I've fiddled with `docker events` and running `docker logs -f <containerID> --details` , which doesn't provide any additional information than what's been contributed. 

@mikesir87 Are there some additional logging or events/message sources you'd recommend we look into?  

Ready to learn and help anyone else tripping up on this. 😄

**Comment by mikesir87** [comment] 2020-04-19 01:50
Thanks for chiming in @t3hcr! The issue isn't a container-related issue, but (for some reason) the SRI checks the browser is running is failing (more details earlier). You can go into the `app/src/static/index.html` file and remove the `integrity` and `crossorigin` attributes from all of the `script` tags. Go ahead and give that a shot and let me know if it works for you. If it works, we can make those changes to the main example (feel free to make a PR if you'd like to contribute!).

**Comment by Monte-Christo** [comment] 2020-04-19 13:16
Hi, thanks for the suggestion, @mikesir87. That worked as far as the Console errors are concerned. But  there is still nothing being displayed but an error message:

```
This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE
```

Should I file a separate issue for this?

**Comment by t3hcr** [comment] 2020-04-19 21:16
Following @mikesir87 suggestion to remove the integrity checks resulted in a working todo app for me.   

I compared the sha256 checksum in WSL and Windows and both showed the same value. (albeit Windows uses caps for letters vs WSL's lower case)  These values did not match the values in index.html.  (maybe they formed differently...?)

That led me to digging over here for what's up with integrity checks: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity (cool feature, I can see why this is a good thing)

So ... the checksums are base64 encoded... 

In WSL, I did the following to get those new values and replaced them in /app/src/static/index.html : 

```
<script src="js/react.production.min.js" integrity="sha256-9+vSqarg29SkRZPgHqGhak6fAnATU3fEPkN1Yw+i25s=" crossorigin="anonymous"></script>
<script src="js/react-dom.production.min.js" integrity="sha256-sp8nn9AyhHakaxibzqQsIsuF/fNQ6UDhwJOMAERMsxs=" crossorigin="anonymous"></script>
<script src="js/react-bootstrap.js" integrity="sha256-BYDF/Xl311qx4ajriU87g3bKXNm6Q7wfjmfDjZvOPLs=" crossorigin="anonymous"></script>
<script src="js/babel.min.js" integrity="sha256-0wja2UfK4fkY4sWYgLIp9NtcZLKen7TjG98MwaHFREw=" crossorigin="anonymous"></script>
```

I rebuilt the container and now it all just works.  I submitted the updated values back as this PR: https://github.com/docker/getting-started/pull/19

Totally not a developer, but... maybe today I am taking a step into it after years of doing infrastructure and systems work. 😄 (or at least be on a path to better support developers in my sphere of influence)

**Comment by mikesir87** [comment] 2020-04-19 21:42
Just commented on the PR, but will post here too... what's interesting is these hashes fail on the Mac. This is the first time I've seen different hashes generated for the same content. So, trying to figure out why that might be going on.

Long-term, I'd like to have the SRI hashes there, as they are a good practice to have (even though not as critical in this case because it's all being served locally and not from a remote source). So, maybe short-term, we just remove the hashes to let people progress while we figure out what's going on.

**Comment by t3hcr** [comment] 2020-04-20 01:59
@Monte-Christo see if the latest update works better for you.  

@mikesir87 - thanks for helping us move this forward so we can just "get started." 😄

**Comment by mikesir87** [comment] 2020-04-20 02:18
No problem @t3hcr! I apologize that there were a few hiccups getting started, but hey! No one said it was perfect and I'm still learning new stuff all the time too! If you run into more issues or have any questions, feel free to reach out!

**Comment by Monte-Christo** [comment] 2020-04-20 05:53
@mikesir87 Thank you, I am in business. After the latest pull, it works.

Strangely enough, though, if I add the new hashes from @t3hcr I again get a blank window, but with no errors in the console. So there is more going on than meets the eye.

Went back to the version straight from the repo and this restored functionality.

**Comment by mustafamalik** [comment] 2020-06-06 18:21
Hi, 
I'm a begginer and facing the similar issue for Window 10 64 bit.

Chrome Version 83.0.4103.61 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/2345989/83951587-e539b780-a84b-11ea-964a-a25927615fd4.png)

**Comment by mdogadailo** [comment] 2020-07-15 20:35
@mustafamalik looks like you are trying to start getting-starting container but not application container.
After http://localhost/tutorial/ you need to create project from http://localhost/tutorial/our-application/ before jump to http://localhost/tutorial/updating-our-app/

**Comment by constructor-igor** [comment] 2021-03-01 18:02
I also cannot start the sample:
Chorome ```http://localhost:3000/``` shows 
```
This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE
```
docker image's log:
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
```

**Comment by yusufunlu** [comment] 2021-03-10 18:53
I supposed my problem is same with aboves but it was this one : https://github.com/docker/getting-started/issues/121
_COPY . /_

**Comment by vishu29** [comment] 2021-04-22 16:15
I also got same error and here are the logs of container 

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up


As such I don't see the error in logs on the browser here is the error
localhost didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by sipi09** [comment] 2021-05-24 00:19
Same problem... The container starts, no error in the logs..

_This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE_

Any idea?

**Comment by jmccormac01** [comment] 2021-05-27 09:53
I am following the tutorial now on Windows 10. I cloned the source from github. Added the Dockerfile as per the tutorial. Ran the container using ```docker run -dp 3000:3000 getting-started```. I get the following in the docker logs:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
```

and then nothing on ```localhost:3000```

![image](https://user-images.githubusercontent.com/1912007/119806016-bb085c00-bed9-11eb-9931-f7e1cdb803e7.png)

Any ideas what might be wrong?

**Comment by bspivey** [comment] 2021-06-28 00:54
I am also seeing a failure for the browser to open the localhost:3000. Any advice for how to start with this tutorial?

**Comment by chupocro** [comment] 2021-07-03 02:30
I was following the tutorial using interactive playground and everything worked well until **Using Bind Mounts** lesson. Since doing the step:

> Now, let's make a change to the app. In the src/static/js/app.js file, let's change the "Add Item" button to simply say "Add".

the browser window is blank.

**Comment by norictech** [comment] 2021-07-12 12:22
`docker run -dp 0.0.0.0:3000:80 getting-started` worked for me. 
I don't know why it is not working if the port on the container was 3000

**Comment by mikesir87** [comment] 2022-12-14 15:38
Seeing this issue has been quiet for a period of time and has covered a variety of topics, we're going to close this issue at this point. If you are still experiencing problems, feel free to start a new issue and we pick up the conversation from there. Thanks all!

**Closed by mikesir87** 2022-12-14 15:38 UTC

**Comment by RajuSuranagi** [comment] 2023-03-08 13:13
So many frequent requests for resolution of this very simple app with no solution by anyone whatsoever. The reason for closing without providing a solution seems strange to me!
