### ISSUE TITLE
Bind Mount instructions do not prove functionality

### ISSUE THREAD

**Issue by krkode** [docker/getting-started#271] opened 2022-04-20 01:29 UTC
The final step (step 7) included in the [Bind Mount tutorial](http://localhost/tutorial/using-bind-mounts/) instructs the user to
"...stop the container and build your new image using `docker build -t getting-started .`"

This command would create a new image based on the Dockerfile included in the /app folder.

However to prove bind mounts enable code changes to take effect without building a new image, I believe the user should instead commit the currently running image to save the bind mount settings with the following command:
`docker commit <container-id> -t getting-started`

After this, the user should be instructed to create a new getting-started container and open "localhost:3000" in their browser.
They should change the code file again and refresh their browser to verify the code changes are visible in the new container without having to rebuild the image.

**Comment by mikesir87** [comment] 2022-12-02 20:30
Hi there @krkode! Apologies for the delay in responding to you. A couple of notes...

- When building images, the best practice is to leverage a `Dockerfile` to build the image and not use `docker commit`. Doing it this way makes it much more easily reproducible. 
- When running the `getting-started` app after doing a build, it should be leveraging _only_ the files that are baked into the image. This helps simulate/test out what it will be like to run the same image in a production-like environment. Because of this, if you make changes to any of the files, you won't see the change when you refresh the browser because the container is only using the files located in the image. That is why bind mounts are so important... they share the files between the host and the container.

If you have more questions, feel free to continue the conversation. Since there isn't an issue with the tutorial itself, I'm going to go ahead and close this issue though. If you find other issues, please don't hesitate to create a new issue to chat about it. Thanks!

**Closed by mikesir87** 2022-12-02 20:30 UTC
